server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/AdvancedPolyclinic
    password: 5535
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  token:
    secret: secretkey
    expired: 3600000